- name: Copy content of directory 'frontend'
  copy:
    src: /workspace/kiv-dce-sem/frontend/
    dest: /tmp/frontend/

- name: Build frontend image
  community.docker.docker_image:
    build:
      path: /tmp/frontend/
    name: frontend
    tag: v3
    push: false
    source: build
    
- name: Run Docker container
  docker_container:
    name: frontend
    image: frontend:v3
    state: started
    ports:
      "80:80"

